import type { FC, KeyboardEvent } from "react";
import { useState } from "react";
import {
  ActionButton,
  Button,
  Input,
  Modal,
  Notification,
  Textarea,
  useToastNotification,
} from "@canonical/react-components";
import { useQueryClient } from "@tanstack/react-query";
import { useEventQueue } from "context/eventQueue";
import { queryKeys } from "util/queryKeys";
import { createInstanceFromMigration } from "api/instances";
import type { InstanceMigrationBundle } from "types/migration";

interface Props {
  close: () => void;
  project: string;
}

// Decode a migration bundle produced by the source cluster. Returns null when
// the pasted text is not a valid bundle.
const decodeBundle = (code: string): InstanceMigrationBundle | null => {
  try {
    const parsed = JSON.parse(atob(code.trim())) as InstanceMigrationBundle;
    if (
      !parsed.instanceName ||
      !Array.isArray(parsed.addresses) ||
      !parsed.operation ||
      !parsed.certificate
    ) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
};

// Target side of a cross-cluster migration. Accepts a migration code pasted from
// the source cluster and pulls the instance into the current project.
const ReceiveMigrationModal: FC<Props> = ({ close, project }) => {
  const toastNotify = useToastNotification();
  const eventQueue = useEventQueue();
  const queryClient = useQueryClient();
  const [code, setCode] = useState("");
  const [name, setName] = useState("");
  const [isLoading, setLoading] = useState(false);

  const bundle = code ? decodeBundle(code) : null;
  const codeIsInvalid = code.trim() !== "" && bundle === null;
  // Default the new instance name to the source name until the user edits it.
  const targetName = name || bundle?.instanceName || "";

  const handleEscKey = (e: KeyboardEvent<HTMLElement>) => {
    if (e.key === "Escape") {
      close();
    }
  };

  const handleFinish = () => {
    queryClient.invalidateQueries({
      queryKey: [queryKeys.instances],
    });
    queryClient.invalidateQueries({
      queryKey: [queryKeys.operations, project],
    });
  };

  const receive = () => {
    if (!bundle) {
      return;
    }
    setLoading(true);
    createInstanceFromMigration(bundle, project, targetName)
      .then((operation) => {
        eventQueue.set(
          operation.metadata.id,
          () => {
            toastNotify.success(
              <>
                Instance <strong>{targetName}</strong> migrated into project{" "}
                <strong>{project}</strong>.
              </>,
            );
          },
          (msg) => {
            toastNotify.failure(
              `Migration failed for instance ${targetName}`,
              new Error(msg),
            );
          },
          handleFinish,
        );
        toastNotify.info(
          <>
            Migration started for instance <strong>{targetName}</strong>.
          </>,
        );
        handleFinish();
      })
      .catch((e) => {
        toastNotify.failure(`Migration failed for instance ${targetName}`, e);
      })
      .finally(() => {
        setLoading(false);
        close();
      });
  };

  return (
    <Modal
      close={close}
      className="receive-migration-modal"
      onKeyDown={handleEscKey}
      title="Receive migration"
    >
      <p>
        Paste the migration code generated by the source cluster to pull the
        instance into project <strong>{project}</strong>.
      </p>
      <Textarea
        id="migration-code"
        label="Migration code"
        rows={5}
        value={code}
        onChange={(e) => {
          setCode(e.target.value);
        }}
        error={codeIsInvalid ? "Not a valid migration code" : undefined}
      />
      {bundle && (
        <>
          <Notification severity="information" title="Source instance">
            {bundle.instanceName} ({bundle.instanceType})
          </Notification>
          <Input
            id="target-instance-name"
            type="text"
            label="New instance name"
            value={targetName}
            onChange={(e) => {
              setName(e.target.value);
            }}
          />
        </>
      )}
      <footer className="p-modal__footer">
        <Button
          className="u-no-margin--bottom"
          type="button"
          appearance="base"
          onClick={close}
        >
          Cancel
        </Button>
        <ActionButton
          appearance="positive"
          className="u-no-margin--bottom"
          onClick={receive}
          loading={isLoading}
          disabled={!bundle || isLoading || targetName === ""}
        >
          Receive
        </ActionButton>
      </footer>
    </Modal>
  );
};

export default ReceiveMigrationModal;
